# Generated by Django 4.0.2 on 2022-03-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idarticle', models.PositiveBigIntegerField(blank=True, db_column='idArticle', null=True)),
                ('idclient', models.PositiveBigIntegerField(blank=True, db_column='idClient', null=True)),
                ('idcommentaire', models.PositiveBigIntegerField(blank=True, db_column='idCommentaire', null=True)),
            ],
            options={
                'db_table': 'commenter',
                'managed': False,
            },
        ),
    ]
