# Generated by Django 4.0.2 on 2022-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('nb', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('url', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'browsing_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idcategorie', models.BigAutoField(db_column='idCategorie', primary_key=True, serialize=False)),
                ('nomcategorie', models.CharField(blank=True, db_column='nomCategorie', max_length=25, null=True)),
            ],
            options={
                'db_table': 'categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.BigAutoField(db_column='idClient', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=25, null=True)),
                ('prenom', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numcommande', models.BigAutoField(db_column='numCommande', primary_key=True, serialize=False)),
                ('prixcommande', models.FloatField(blank=True, db_column='prixCommande', null=True)),
                ('articletotal', models.IntegerField(blank=True, db_column='articleTotal', null=True)),
                ('datecommande', models.DateField(blank=True, db_column='dateCommande', null=True)),
            ],
            options={
                'db_table': 'commande',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('idarticle', models.PositiveBigIntegerField(db_column='idArticle', primary_key=True, serialize=False)),
                ('idcategorie', models.PositiveBigIntegerField(db_column='idCategorie')),
            ],
            options={
                'db_table': 'ranger',
                'managed': False,
            },
        ),
    ]
